os: linux
language: node_js
node_js: '12'

services:
  - docker
  
env:
  global:
    - IMAGE=trzeci/emscripten
    - NAME=emscipten
    - RUN="docker exec -it emscipten"
    - EMSCRIPTEN_VERSION=1.37.26

install: skip

before_script:
  - docker pull $IMAGE
  - docker images
  - docker run -dit --name $NAME -e EMSCRIPTEN_VERSION -v $(pwd)/libheif:/src -w /src $IMAGE bash
  - sleep 2
  - docker ps -a
  - $RUN cat /etc/os-release

script:
  - $RUN ./scripts/install-ci-linux.sh
  - $RUN ./scripts/prepare-ci.sh
  - $RUN ./scripts/run-ci.sh
  - ls libheif
