language: cpp
compiler: gcc
os: linux
  
env:
  global:
    - EMSCRIPTEN_VERSION=1.37.26

install: skip

before_install:
  - cd $TRAVIS_BUILD_DIR
  - cd libheif
  - ./scripts/install-ci-linux.sh

before_script:
  - cd $TRAVIS_BUILD_DIR
  - cd libheif
  - ./scripts/prepare-ci.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - cd libheif
  - ./scripts/run-ci.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - cd libheif
  - ./build-emscripten.sh
  - ls -la
